name = "Ne Artemi Silebox Rpg Modpack"
author = "Silebox & ArtCanDy"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f989be970b9ec427e3bd80f5ae6f5e385c3deb54420c28da0ff556c03177c489"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
