name = "Ne Artemi Silebox Rpg Modpack"
author = "Silebox & ArtCanDy"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c92cbcea603e5f3cc795e8a081c419f3cd40d48aedef056a9f7de7f17b2caad2"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
