name = "Ne Artemi Silebox Rpg Modpack"
author = "Silebox & ArtCanDy"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e863b3e02bc3633b2f76dc1ed03f67e1639f0f2294e0aa29d7f5401aaa8ddff4"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
